services:
  web:
    build: ./
    command: flask run
    volumes:
        - ./:/usr/src/app/
    ports:
      - 5000:8080
    depends_on:
      - db
  db:
    image: postgres:14
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    environment:
    - POSTGRES_USER=sactest
    - POSTGRES_PASSWORD=sactest
    - POSTGRES_DB=sacdb
  db-web:
    image: dpage/pgadmin4
    volumes:
    - pgadmin:/var/lib/pgadmin
    environment:
    - PGADMIN_DEFAULT_EMAIL=admin@pgadmin.com
    - PGADMIN_DEFAULT_PASSWORD=password
    - PGADMIN_LISTEN_PORT=80
    ports:
    - 15432:80
    depends_on:
    - db
  locust:
    build: ./
    command: locust
    volumes:
        - ./:/usr/src/app/
    ports:
      - 8089:8089
    depends_on:
      - web


volumes:
  postgres_data: 
  pgadmin:
  
