# This is a basic workflow that is manually triggered

name: Push Changes to Server
on: 
  push:
    branches:
      - main
  pull_request:
      types: [opened, synchronize, reopened, closed]
      branches:
      - main
permissions:
  issues: write
  contents: read
  pull-requests: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Execute remote SSH
      run: |
        sudo apt-get install sshpass
        sshpass -p '${{ secrets.server_pass }}' ssh -v -o StrictHostKeyChecking=no ${{ secrets.serverlogin }}@ $ {{ secrets.server_addr }}  <<'ENDSSH'
        sudo systemctl restart sacsock
        ${{ secrets.server_pass }}
        
      
      
