# This is a basic workflow that is manually triggered

name: Push Changes to Server
on: 
  push:
    branches:
      - main
  pull_request:
      types: [opened, synchronize, reopened, closed]
      branches:
      - main
permissions:
  issues: write
  contents: read
  pull-requests: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Set up SSH key
      run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ARTIFACT_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo ${{ secrets.ARTIFACT_HOST }} >> ~/.ssh/known_hosts
          sudo apt-get install sshpass
    - name: Execute remote SSH
      run: |
        sshpass -p '${{ secrets.SERVER_PASS }}' ssh -v -o StrictHostKeyChecking=no ${{ secrets.SERVERLOGIN }}@ ${{ secrets.SERVER_ADDR }} <<'ENDSSH'
        sudo systemctl restart sacsock
        ${{ secrets.SERVER_PASS }}
        
      
      
